### ISSUE TITLE
I got an error when run packages/example

### ISSUE THREAD

**Issue by forsigner** [Lucifier129/farrow#27]
I got an error when run packages/example as follow:

```bash
➜  example git:(master) ✗ yarn dev
yarn run v1.22.4
$ farrow dev
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'fs/promises'
Require stack:
- /Users/forsigner/repos/github/farrow/packages/example/node_modules/farrow/dist/bundler/server.js
- /Users/forsigner/repos/github/farrow/packages/example/node_modules/farrow/dist/dev.js
- /Users/forsigner/repos/github/farrow/packages/example/node_modules/farrow/scripts/dev.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/forsigner/repos/github/farrow/packages/example/node_modules/farrow/dist/bundler/server.js:10:42)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/forsigner/repos/github/farrow/packages/example/node_modules/farrow/dist/bundler/server.js',
    '/Users/forsigner/repos/github/farrow/packages/example/node_modules/farrow/dist/dev.js',
    '/Users/forsigner/repos/github/farrow/packages/example/node_modules/farrow/scripts/dev.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Lucifier129** [comment]
Please upgrade your node.js to v14.0.0 or greater.

See node.js [documentation](https://github.com/Lucifier129/farrow#environment-requirement) about `fs/promise`

**Comment by forsigner** [comment]
It works, thx~
