### ISSUE TITLE
farrow-example can't build after bootstraping with lerna

### ISSUE THREAD

**Issue by suica** [Lucifier129/farrow#33]
# Problem
farrow-example cannot run if the monorepo is merely initialized by `lerna bootstrap` (or just `npm run init`). 

When executing `npm run dev` for farrow-example (in `./packages/example`), there will be an error:
```
> farrow-example@1.5.1 dev /Users/farrow-test/workspace/temp/farrow/packages/example
> farrow dev

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '../dist/dev'
Require stack:
- /Users/farrow-test/workspace/temp/farrow/packages/farrow/scripts/dev.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/farrow-test/workspace/temp/farrow/packages/farrow/scripts/dev.js:2:13)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/farrow-test/workspace/temp/farrow/packages/farrow/scripts/dev.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! farrow-example@1.5.1 dev: `farrow dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the farrow-example@1.5.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/farrow-test/.npm/_logs/2021-01-16T15_36_27_978Z-debug.log
```

This issue also happens in farrow 1.5.0 repo.

# How to reproduce
1. clone the repo (or just delete all node_modules folders).
2. run `npm run init`.
3. `cd` to `./packages/example`
4. run `npm run dev`.

# Workarounds
Since lerna reuses modules, the farrow-example package just uses the `farrow` in a linked fashion.
Removing node_modules and *package-lock.json* in `example` folder then a rerun of `npm i` in `exmaple` folder to reinstall dependencies could temporarily fix this.

**Comment by Lucifier129** [comment]
`npm run build` is necessary, we should add this script to `npm run init`.
